// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: emergencia.proto

package emergencia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emergencia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float32                `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,4,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emergencia) Reset() {
	*x = Emergencia{}
	mi := &file_emergencia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emergencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emergencia) ProtoMessage() {}

func (x *Emergencia) ProtoReflect() protoreflect.Message {
	mi := &file_emergencia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emergencia.ProtoReflect.Descriptor instead.
func (*Emergencia) Descriptor() ([]byte, []int) {
	return file_emergencia_proto_rawDescGZIP(), []int{0}
}

func (x *Emergencia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Emergencia) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Emergencia) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Emergencia) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

type EmergenciasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emergencias   []*Emergencia          `protobuf:"bytes,1,rep,name=emergencias,proto3" json:"emergencias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergenciasRequest) Reset() {
	*x = EmergenciasRequest{}
	mi := &file_emergencia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergenciasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergenciasRequest) ProtoMessage() {}

func (x *EmergenciasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emergencia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergenciasRequest.ProtoReflect.Descriptor instead.
func (*EmergenciasRequest) Descriptor() ([]byte, []int) {
	return file_emergencia_proto_rawDescGZIP(), []int{1}
}

func (x *EmergenciasRequest) GetEmergencias() []*Emergencia {
	if x != nil {
		return x.Emergencias
	}
	return nil
}

type EmergenciaAsignada struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmergencyId   int32                  `protobuf:"varint,1,opt,name=emergency_id,json=emergencyId,proto3" json:"emergency_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float32                `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,5,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	DronId        string                 `protobuf:"bytes,6,opt,name=dron_id,json=dronId,proto3" json:"dron_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergenciaAsignada) Reset() {
	*x = EmergenciaAsignada{}
	mi := &file_emergencia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergenciaAsignada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergenciaAsignada) ProtoMessage() {}

func (x *EmergenciaAsignada) ProtoReflect() protoreflect.Message {
	mi := &file_emergencia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergenciaAsignada.ProtoReflect.Descriptor instead.
func (*EmergenciaAsignada) Descriptor() ([]byte, []int) {
	return file_emergencia_proto_rawDescGZIP(), []int{2}
}

func (x *EmergenciaAsignada) GetEmergencyId() int32 {
	if x != nil {
		return x.EmergencyId
	}
	return 0
}

func (x *EmergenciaAsignada) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmergenciaAsignada) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EmergenciaAsignada) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EmergenciaAsignada) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

func (x *EmergenciaAsignada) GetDronId() string {
	if x != nil {
		return x.DronId
	}
	return ""
}

// Respuesta simple
type Respuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	mi := &file_emergencia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_emergencia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_emergencia_proto_rawDescGZIP(), []int{3}
}

func (x *Respuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type MensajeMonitoreo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contenido     string                 `protobuf:"bytes,1,opt,name=contenido,proto3" json:"contenido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MensajeMonitoreo) Reset() {
	*x = MensajeMonitoreo{}
	mi := &file_emergencia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MensajeMonitoreo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeMonitoreo) ProtoMessage() {}

func (x *MensajeMonitoreo) ProtoReflect() protoreflect.Message {
	mi := &file_emergencia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeMonitoreo.ProtoReflect.Descriptor instead.
func (*MensajeMonitoreo) Descriptor() ([]byte, []int) {
	return file_emergencia_proto_rawDescGZIP(), []int{4}
}

func (x *MensajeMonitoreo) GetContenido() string {
	if x != nil {
		return x.Contenido
	}
	return ""
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_emergencia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_emergencia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_emergencia_proto_rawDescGZIP(), []int{5}
}

var File_emergencia_proto protoreflect.FileDescriptor

const file_emergencia_proto_rawDesc = "" +
	"\n" +
	"\x10emergencia.proto\x12\n" +
	"emergencia\"x\n" +
	"\n" +
	"Emergencia\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x02R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x04 \x01(\x05R\tmagnitude\"N\n" +
	"\x12EmergenciasRequest\x128\n" +
	"\vemergencias\x18\x01 \x03(\v2\x16.emergencia.EmergenciaR\vemergencias\"\xbc\x01\n" +
	"\x12EmergenciaAsignada\x12!\n" +
	"\femergency_id\x18\x01 \x01(\x05R\vemergencyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x02R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x05 \x01(\x05R\tmagnitude\x12\x17\n" +
	"\adron_id\x18\x06 \x01(\tR\x06dronId\"%\n" +
	"\tRespuesta\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"0\n" +
	"\x10MensajeMonitoreo\x12\x1c\n" +
	"\tcontenido\x18\x01 \x01(\tR\tcontenido\"\a\n" +
	"\x05Vacio2W\n" +
	"\tAsignador\x12J\n" +
	"\x11EnviarEmergencias\x12\x1e.emergencia.EmergenciasRequest\x1a\x15.emergencia.Respuesta2R\n" +
	"\x04Dron\x12J\n" +
	"\x11AtenderEmergencia\x12\x1e.emergencia.EmergenciaAsignada\x1a\x15.emergencia.Respuesta2P\n" +
	"\tMonitoreo\x12C\n" +
	"\x0eStreamMensajes\x12\x11.emergencia.Vacio\x1a\x1c.emergencia.MensajeMonitoreo0\x01B\x0eZ\f./emergenciab\x06proto3"

var (
	file_emergencia_proto_rawDescOnce sync.Once
	file_emergencia_proto_rawDescData []byte
)

func file_emergencia_proto_rawDescGZIP() []byte {
	file_emergencia_proto_rawDescOnce.Do(func() {
		file_emergencia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emergencia_proto_rawDesc), len(file_emergencia_proto_rawDesc)))
	})
	return file_emergencia_proto_rawDescData
}

var file_emergencia_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_emergencia_proto_goTypes = []any{
	(*Emergencia)(nil),         // 0: emergencia.Emergencia
	(*EmergenciasRequest)(nil), // 1: emergencia.EmergenciasRequest
	(*EmergenciaAsignada)(nil), // 2: emergencia.EmergenciaAsignada
	(*Respuesta)(nil),          // 3: emergencia.Respuesta
	(*MensajeMonitoreo)(nil),   // 4: emergencia.MensajeMonitoreo
	(*Vacio)(nil),              // 5: emergencia.Vacio
}
var file_emergencia_proto_depIdxs = []int32{
	0, // 0: emergencia.EmergenciasRequest.emergencias:type_name -> emergencia.Emergencia
	1, // 1: emergencia.Asignador.EnviarEmergencias:input_type -> emergencia.EmergenciasRequest
	2, // 2: emergencia.Dron.AtenderEmergencia:input_type -> emergencia.EmergenciaAsignada
	5, // 3: emergencia.Monitoreo.StreamMensajes:input_type -> emergencia.Vacio
	3, // 4: emergencia.Asignador.EnviarEmergencias:output_type -> emergencia.Respuesta
	3, // 5: emergencia.Dron.AtenderEmergencia:output_type -> emergencia.Respuesta
	4, // 6: emergencia.Monitoreo.StreamMensajes:output_type -> emergencia.MensajeMonitoreo
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_emergencia_proto_init() }
func file_emergencia_proto_init() {
	if File_emergencia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emergencia_proto_rawDesc), len(file_emergencia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_emergencia_proto_goTypes,
		DependencyIndexes: file_emergencia_proto_depIdxs,
		MessageInfos:      file_emergencia_proto_msgTypes,
	}.Build()
	File_emergencia_proto = out.File
	file_emergencia_proto_goTypes = nil
	file_emergencia_proto_depIdxs = nil
}
